import {
  AfterViewInit,
  Component,
  ElementRef,
  EventEmitter,
  HostBinding,
  OnInit,
  Output,
  QueryList,
  ViewChild,
  ViewChildren,
} from '@angular/core';
import { catchError, map, switchMap } from 'rxjs/operators';
import { of, Subscription } from 'rxjs';
import { MetricModel } from '../../../profile-table/models/metric.model';
import { Router } from '@angular/router';
import { QanProfileService } from '../../../profile/qan-profile.service';
import { ObjectDetailsService } from '../../../../pmm-api-services/services/object-details.service';
import { DetailsSparklineModel } from '../../models/details-sparkline.model';
import { ObjectDetails } from '../../../profile/interfaces/object-details.interface';

@Component({
  selector: 'app-details-table',
  templateUrl: './details-table.component.html',
  styleUrls: ['./details-table.component.css'],
})
export class DetailsTableComponent implements OnInit, AfterViewInit {
  @ViewChild('table', { static: true }) table: ElementRef;
  @ViewChildren('detailsTableRows') tableRows: QueryList<any>;
  @HostBinding('class.frame') isLoading = true;
  @Output() finishRender = new EventEmitter();

  protected dbName: string;
  public fingerprint: string;
  public currentParams: any;
  public dimension: string;
  public isTotal = false;
  public details: any = {};
  private group_by$: Subscription;
  private details$: Subscription;
  private firstDetails: ObjectDetails;
  public queryCount: any;

  constructor(
    protected router: Router,
    protected qanProfileService: QanProfileService,
    protected objectDetailsService: ObjectDetailsService
  ) {
    this.isLoading = true;
    this.details$ = this.qanProfileService.getProfileInfo.details
      .pipe(
        switchMap(parsedParams => {
          this.isLoading = true;
          this.currentParams = parsedParams;
          return this.getDetailsData(parsedParams);
        })
      )
      .subscribe(response => {
        this.details = response;
        this.details.metrics = this.detailsTableOrder(response['metrics']);
        this.details.metricDictionary = response['metrics'].reduce(
          (metricsDict, metric) => {
            metricsDict[metric.metricName] = metric;
            return metricsDict;
          },
          {}
        );
        this.queryCount = this.details.metrics.find(
          item => item.metricName === 'num_queries'
        ).stats['sum'];
        this.isTotal = !this.currentParams.filter_by;
        this.isLoading = false;
      });

    this.group_by$ = this.qanProfileService.getGroupBy.subscribe(
      () => (this.details.metrics = [])
    );
  }

  ngOnInit() {
    // this.firstDetails = this.qanProfileService.getCurrentDetails;
    // this.getDetailsData(this.firstDetails).subscribe(response => {
    //   this.details = response;
    //   this.details.metrics = this.detailsTableOrder(response['metrics']);
    //   this.isLoading = false;
    // });
  }

  ngAfterViewInit() {
    this.tableRows.changes.subscribe(() => {
      this.setLabelsHeight();
    });
  }

  createSparklineModel(sparklines, name) {
    return sparklines.map(item => new DetailsSparklineModel(item, name));
  }

  setLabelsHeight() {
    const tableHeight = this.table.nativeElement.offsetHeight;
    this.finishRender.emit(tableHeight);
  }

  detailsTableOrder(detailsTableData) {
    return detailsTableData.sort((a, b) => this.sortDetails(a, b));
  }

  getDetailsData(detailsParams) {
    return this.objectDetailsService.GetMetrics(detailsParams).pipe(
      catchError(err => of({ metrics: [], sparkline: [] })),
      map(() => {
        const response = {
          metrics: {
            blk_read_time: {},
            blk_write_time: {},
            bytes_sent: {},
            docs_returned: {},
            docs_scanned: {},
            filesort: {},
            filesort_on_disk: {},
            full_join: {},
            full_scan: { rate: 0.062129628, sum: 2684 },
            innodb_io_r_bytes: {},
            innodb_io_r_ops: {},
            innodb_io_r_wait: {},
            innodb_pages_distinct: {},
            innodb_queue_wait: {},
            innodb_rec_lock_wait: {},
            local_blks_dirtied: {},
            local_blks_hit: {},
            local_blks_read: {},
            local_blks_written: {},
            lock_time: {
              rate: 0.000004934792,
              cnt: 1342,
              sum: 0.213183,
              avg: 0.0001588547,
            },
            merge_passes: {},
            no_good_index_used: {},
            no_index_used: { rate: 0.031064814, sum: 1342 },
            num_queries: { rate: 0.031064814, sum: 1342 },
            num_queries_with_errors: {},
            num_queries_with_warnings: {},
            qc_hit: {},
            query_length: {},
            query_time: {
              rate: 0.000053529526,
              cnt: 1342,
              sum: 2.3124754,
              avg: 0.0017231561,
            },
            response_length: {},
            rows_affected: {},
            rows_examined: {
              rate: 15.532408,
              cnt: 1342,
              sum: 671000,
              avg: 500,
            },
            rows_read: {},
            rows_sent: { rate: 15.532408, cnt: 1342, sum: 671000, avg: 500 },
            select_full_range_join: {},
            select_range: {},
            select_range_check: {},
            shared_blks_dirtied: {},
            shared_blks_hit: {},
            shared_blks_read: {},
            shared_blks_written: {},
            sort_range: {},
            sort_rows: {},
            sort_scan: {},
            temp_blks_read: {},
            temp_blks_written: {},
            tmp_disk_tables: {},
            tmp_table: {},
            tmp_table_on_disk: {},
            tmp_table_sizes: {},
            tmp_tables: { rate: 0.031064814, cnt: 1342, sum: 1342, avg: 1 },
          },
          sparkline: [
            { time_frame: 360, timestamp: '2020-01-28T14:46:00Z' },
            {
              point: 1,
              time_frame: 360,
              timestamp: '2020-01-28T14:40:00Z',
              load: 0.00018359465,
              num_queries_per_sec: 0.06666667,
              m_query_time_sum_per_sec: 0.00018359465,
              m_lock_time_sum_per_sec: 0.000018883333,
              m_rows_sent_sum_per_sec: 33.333332,
              m_rows_examined_sum_per_sec: 33.333332,
              m_rows_affected_sum_per_sec: 'NaN',
              m_rows_read_sum_per_sec: 'NaN',
              m_merge_passes_sum_per_sec: 'NaN',
              m_innodb_io_r_ops_sum_per_sec: 'NaN',
              m_innodb_io_r_bytes_sum_per_sec: 'NaN',
              m_innodb_io_r_wait_sum_per_sec: 'NaN',
              m_innodb_rec_lock_wait_sum_per_sec: 'NaN',
              m_innodb_queue_wait_sum_per_sec: 'NaN',
              m_innodb_pages_distinct_sum_per_sec: 'NaN',
              m_query_length_sum_per_sec: 'NaN',
              m_bytes_sent_sum_per_sec: 'NaN',
              m_tmp_tables_sum_per_sec: 0.06666667,
              m_tmp_disk_tables_sum_per_sec: 'NaN',
              m_tmp_table_sizes_sum_per_sec: 'NaN',
              m_qc_hit_sum_per_sec: 'NaN',
              m_full_scan_sum_per_sec: 0.13333334,
              m_full_join_sum_per_sec: 'NaN',
              m_tmp_table_sum_per_sec: 'NaN',
              m_tmp_table_on_disk_sum_per_sec: 'NaN',
              m_filesort_sum_per_sec: 'NaN',
              m_filesort_on_disk_sum_per_sec: 'NaN',
              m_select_full_range_join_sum_per_sec: 'NaN',
              m_select_range_sum_per_sec: 'NaN',
              m_select_range_check_sum_per_sec: 'NaN',
              m_sort_range_sum_per_sec: 'NaN',
              m_sort_rows_sum_per_sec: 'NaN',
              m_sort_scan_sum_per_sec: 'NaN',
              m_no_index_used_sum_per_sec: 0.06666667,
              m_no_good_index_used_sum_per_sec: 'NaN',
              m_docs_returned_sum_per_sec: 'NaN',
              m_response_length_sum_per_sec: 'NaN',
              m_docs_scanned_sum_per_sec: 'NaN',
              m_shared_blks_hit_sum_per_sec: 'NaN',
              m_shared_blks_read_sum_per_sec: 'NaN',
              m_shared_blks_dirtied_sum_per_sec: 'NaN',
              m_shared_blks_written_sum_per_sec: 'NaN',
              m_local_blks_hit_sum_per_sec: 'NaN',
              m_local_blks_read_sum_per_sec: 'NaN',
              m_local_blks_dirtied_sum_per_sec: 'NaN',
              m_local_blks_written_sum_per_sec: 'NaN',
              m_temp_blks_read_sum_per_sec: 'NaN',
              m_temp_blks_written_sum_per_sec: 'NaN',
              m_blk_read_time_sum_per_sec: 'NaN',
              m_blk_write_time_sum_per_sec: 'NaN',
            },
            {
              point: 2,
              time_frame: 360,
              timestamp: '2020-01-28T14:34:00Z',
              load: 0.00067928643,
              num_queries_per_sec: 0.4,
              m_query_time_sum_per_sec: 0.00067928643,
              m_lock_time_sum_per_sec: 0.00006116111,
              m_rows_sent_sum_per_sec: 200,
              m_rows_examined_sum_per_sec: 200,
              m_rows_affected_sum_per_sec: 'NaN',
              m_rows_read_sum_per_sec: 'NaN',
              m_merge_passes_sum_per_sec: 'NaN',
              m_innodb_io_r_ops_sum_per_sec: 'NaN',
              m_innodb_io_r_bytes_sum_per_sec: 'NaN',
              m_innodb_io_r_wait_sum_per_sec: 'NaN',
              m_innodb_rec_lock_wait_sum_per_sec: 'NaN',
              m_innodb_queue_wait_sum_per_sec: 'NaN',
              m_innodb_pages_distinct_sum_per_sec: 'NaN',
              m_query_length_sum_per_sec: 'NaN',
              m_bytes_sent_sum_per_sec: 'NaN',
              m_tmp_tables_sum_per_sec: 0.4,
              m_tmp_disk_tables_sum_per_sec: 'NaN',
              m_tmp_table_sizes_sum_per_sec: 'NaN',
              m_qc_hit_sum_per_sec: 'NaN',
              m_full_scan_sum_per_sec: 0.8,
              m_full_join_sum_per_sec: 'NaN',
              m_tmp_table_sum_per_sec: 'NaN',
              m_tmp_table_on_disk_sum_per_sec: 'NaN',
              m_filesort_sum_per_sec: 'NaN',
              m_filesort_on_disk_sum_per_sec: 'NaN',
              m_select_full_range_join_sum_per_sec: 'NaN',
              m_select_range_sum_per_sec: 'NaN',
              m_select_range_check_sum_per_sec: 'NaN',
              m_sort_range_sum_per_sec: 'NaN',
              m_sort_rows_sum_per_sec: 'NaN',
              m_sort_scan_sum_per_sec: 'NaN',
              m_no_index_used_sum_per_sec: 0.4,
              m_no_good_index_used_sum_per_sec: 'NaN',
              m_docs_returned_sum_per_sec: 'NaN',
              m_response_length_sum_per_sec: 'NaN',
              m_docs_scanned_sum_per_sec: 'NaN',
              m_shared_blks_hit_sum_per_sec: 'NaN',
              m_shared_blks_read_sum_per_sec: 'NaN',
              m_shared_blks_dirtied_sum_per_sec: 'NaN',
              m_shared_blks_written_sum_per_sec: 'NaN',
              m_local_blks_hit_sum_per_sec: 'NaN',
              m_local_blks_read_sum_per_sec: 'NaN',
              m_local_blks_dirtied_sum_per_sec: 'NaN',
              m_local_blks_written_sum_per_sec: 'NaN',
              m_temp_blks_read_sum_per_sec: 'NaN',
              m_temp_blks_written_sum_per_sec: 'NaN',
              m_blk_read_time_sum_per_sec: 'NaN',
              m_blk_write_time_sum_per_sec: 'NaN',
            },
            {
              point: 3,
              time_frame: 360,
              timestamp: '2020-01-28T14:28:00Z',
              load: 0.00069153996,
              num_queries_per_sec: 0.4,
              m_query_time_sum_per_sec: 0.00069153996,
              m_lock_time_sum_per_sec: 0.000055766668,
              m_rows_sent_sum_per_sec: 200,
              m_rows_examined_sum_per_sec: 200,
              m_rows_affected_sum_per_sec: 'NaN',
              m_rows_read_sum_per_sec: 'NaN',
              m_merge_passes_sum_per_sec: 'NaN',
              m_innodb_io_r_ops_sum_per_sec: 'NaN',
              m_innodb_io_r_bytes_sum_per_sec: 'NaN',
              m_innodb_io_r_wait_sum_per_sec: 'NaN',
              m_innodb_rec_lock_wait_sum_per_sec: 'NaN',
              m_innodb_queue_wait_sum_per_sec: 'NaN',
              m_innodb_pages_distinct_sum_per_sec: 'NaN',
              m_query_length_sum_per_sec: 'NaN',
              m_bytes_sent_sum_per_sec: 'NaN',
              m_tmp_tables_sum_per_sec: 0.4,
              m_tmp_disk_tables_sum_per_sec: 'NaN',
              m_tmp_table_sizes_sum_per_sec: 'NaN',
              m_qc_hit_sum_per_sec: 'NaN',
              m_full_scan_sum_per_sec: 0.8,
              m_full_join_sum_per_sec: 'NaN',
              m_tmp_table_sum_per_sec: 'NaN',
              m_tmp_table_on_disk_sum_per_sec: 'NaN',
              m_filesort_sum_per_sec: 'NaN',
              m_filesort_on_disk_sum_per_sec: 'NaN',
              m_select_full_range_join_sum_per_sec: 'NaN',
              m_select_range_sum_per_sec: 'NaN',
              m_select_range_check_sum_per_sec: 'NaN',
              m_sort_range_sum_per_sec: 'NaN',
              m_sort_rows_sum_per_sec: 'NaN',
              m_sort_scan_sum_per_sec: 'NaN',
              m_no_index_used_sum_per_sec: 0.4,
              m_no_good_index_used_sum_per_sec: 'NaN',
              m_docs_returned_sum_per_sec: 'NaN',
              m_response_length_sum_per_sec: 'NaN',
              m_docs_scanned_sum_per_sec: 'NaN',
              m_shared_blks_hit_sum_per_sec: 'NaN',
              m_shared_blks_read_sum_per_sec: 'NaN',
              m_shared_blks_dirtied_sum_per_sec: 'NaN',
              m_shared_blks_written_sum_per_sec: 'NaN',
              m_local_blks_hit_sum_per_sec: 'NaN',
              m_local_blks_read_sum_per_sec: 'NaN',
              m_local_blks_dirtied_sum_per_sec: 'NaN',
              m_local_blks_written_sum_per_sec: 'NaN',
              m_temp_blks_read_sum_per_sec: 'NaN',
              m_temp_blks_written_sum_per_sec: 'NaN',
              m_blk_read_time_sum_per_sec: 'NaN',
              m_blk_write_time_sum_per_sec: 'NaN',
            },
            {
              point: 4,
              time_frame: 360,
              timestamp: '2020-01-28T14:22:00Z',
              load: 0.000645793,
              num_queries_per_sec: 0.4,
              m_query_time_sum_per_sec: 0.000645793,
              m_lock_time_sum_per_sec: 0.00006686944,
              m_rows_sent_sum_per_sec: 200,
              m_rows_examined_sum_per_sec: 200,
              m_rows_affected_sum_per_sec: 'NaN',
              m_rows_read_sum_per_sec: 'NaN',
              m_merge_passes_sum_per_sec: 'NaN',
              m_innodb_io_r_ops_sum_per_sec: 'NaN',
              m_innodb_io_r_bytes_sum_per_sec: 'NaN',
              m_innodb_io_r_wait_sum_per_sec: 'NaN',
              m_innodb_rec_lock_wait_sum_per_sec: 'NaN',
              m_innodb_queue_wait_sum_per_sec: 'NaN',
              m_innodb_pages_distinct_sum_per_sec: 'NaN',
              m_query_length_sum_per_sec: 'NaN',
              m_bytes_sent_sum_per_sec: 'NaN',
              m_tmp_tables_sum_per_sec: 0.4,
              m_tmp_disk_tables_sum_per_sec: 'NaN',
              m_tmp_table_sizes_sum_per_sec: 'NaN',
              m_qc_hit_sum_per_sec: 'NaN',
              m_full_scan_sum_per_sec: 0.8,
              m_full_join_sum_per_sec: 'NaN',
              m_tmp_table_sum_per_sec: 'NaN',
              m_tmp_table_on_disk_sum_per_sec: 'NaN',
              m_filesort_sum_per_sec: 'NaN',
              m_filesort_on_disk_sum_per_sec: 'NaN',
              m_select_full_range_join_sum_per_sec: 'NaN',
              m_select_range_sum_per_sec: 'NaN',
              m_select_range_check_sum_per_sec: 'NaN',
              m_sort_range_sum_per_sec: 'NaN',
              m_sort_rows_sum_per_sec: 'NaN',
              m_sort_scan_sum_per_sec: 'NaN',
              m_no_index_used_sum_per_sec: 0.4,
              m_no_good_index_used_sum_per_sec: 'NaN',
              m_docs_returned_sum_per_sec: 'NaN',
              m_response_length_sum_per_sec: 'NaN',
              m_docs_scanned_sum_per_sec: 'NaN',
              m_shared_blks_hit_sum_per_sec: 'NaN',
              m_shared_blks_read_sum_per_sec: 'NaN',
              m_shared_blks_dirtied_sum_per_sec: 'NaN',
              m_shared_blks_written_sum_per_sec: 'NaN',
              m_local_blks_hit_sum_per_sec: 'NaN',
              m_local_blks_read_sum_per_sec: 'NaN',
              m_local_blks_dirtied_sum_per_sec: 'NaN',
              m_local_blks_written_sum_per_sec: 'NaN',
              m_temp_blks_read_sum_per_sec: 'NaN',
              m_temp_blks_written_sum_per_sec: 'NaN',
              m_blk_read_time_sum_per_sec: 'NaN',
              m_blk_write_time_sum_per_sec: 'NaN',
            },
            {
              point: 5,
              time_frame: 360,
              timestamp: '2020-01-28T14:16:00Z',
              load: 0.00070403673,
              num_queries_per_sec: 0.4,
              m_query_time_sum_per_sec: 0.00070403673,
              m_lock_time_sum_per_sec: 0.00006665,
              m_rows_sent_sum_per_sec: 200,
              m_rows_examined_sum_per_sec: 200,
              m_rows_affected_sum_per_sec: 'NaN',
              m_rows_read_sum_per_sec: 'NaN',
              m_merge_passes_sum_per_sec: 'NaN',
              m_innodb_io_r_ops_sum_per_sec: 'NaN',
              m_innodb_io_r_bytes_sum_per_sec: 'NaN',
              m_innodb_io_r_wait_sum_per_sec: 'NaN',
              m_innodb_rec_lock_wait_sum_per_sec: 'NaN',
              m_innodb_queue_wait_sum_per_sec: 'NaN',
              m_innodb_pages_distinct_sum_per_sec: 'NaN',
              m_query_length_sum_per_sec: 'NaN',
              m_bytes_sent_sum_per_sec: 'NaN',
              m_tmp_tables_sum_per_sec: 0.4,
              m_tmp_disk_tables_sum_per_sec: 'NaN',
              m_tmp_table_sizes_sum_per_sec: 'NaN',
              m_qc_hit_sum_per_sec: 'NaN',
              m_full_scan_sum_per_sec: 0.8,
              m_full_join_sum_per_sec: 'NaN',
              m_tmp_table_sum_per_sec: 'NaN',
              m_tmp_table_on_disk_sum_per_sec: 'NaN',
              m_filesort_sum_per_sec: 'NaN',
              m_filesort_on_disk_sum_per_sec: 'NaN',
              m_select_full_range_join_sum_per_sec: 'NaN',
              m_select_range_sum_per_sec: 'NaN',
              m_select_range_check_sum_per_sec: 'NaN',
              m_sort_range_sum_per_sec: 'NaN',
              m_sort_rows_sum_per_sec: 'NaN',
              m_sort_scan_sum_per_sec: 'NaN',
              m_no_index_used_sum_per_sec: 0.4,
              m_no_good_index_used_sum_per_sec: 'NaN',
              m_docs_returned_sum_per_sec: 'NaN',
              m_response_length_sum_per_sec: 'NaN',
              m_docs_scanned_sum_per_sec: 'NaN',
              m_shared_blks_hit_sum_per_sec: 'NaN',
              m_shared_blks_read_sum_per_sec: 'NaN',
              m_shared_blks_dirtied_sum_per_sec: 'NaN',
              m_shared_blks_written_sum_per_sec: 'NaN',
              m_local_blks_hit_sum_per_sec: 'NaN',
              m_local_blks_read_sum_per_sec: 'NaN',
              m_local_blks_dirtied_sum_per_sec: 'NaN',
              m_local_blks_written_sum_per_sec: 'NaN',
              m_temp_blks_read_sum_per_sec: 'NaN',
              m_temp_blks_written_sum_per_sec: 'NaN',
              m_blk_read_time_sum_per_sec: 'NaN',
              m_blk_write_time_sum_per_sec: 'NaN',
            },
            {
              point: 6,
              time_frame: 360,
              timestamp: '2020-01-28T14:10:00Z',
              load: 0.0006622182,
              num_queries_per_sec: 0.4,
              m_query_time_sum_per_sec: 0.0006622182,
              m_lock_time_sum_per_sec: 0.000061872226,
              m_rows_sent_sum_per_sec: 200,
              m_rows_examined_sum_per_sec: 200,
              m_rows_affected_sum_per_sec: 'NaN',
              m_rows_read_sum_per_sec: 'NaN',
              m_merge_passes_sum_per_sec: 'NaN',
              m_innodb_io_r_ops_sum_per_sec: 'NaN',
              m_innodb_io_r_bytes_sum_per_sec: 'NaN',
              m_innodb_io_r_wait_sum_per_sec: 'NaN',
              m_innodb_rec_lock_wait_sum_per_sec: 'NaN',
              m_innodb_queue_wait_sum_per_sec: 'NaN',
              m_innodb_pages_distinct_sum_per_sec: 'NaN',
              m_query_length_sum_per_sec: 'NaN',
              m_bytes_sent_sum_per_sec: 'NaN',
              m_tmp_tables_sum_per_sec: 0.4,
              m_tmp_disk_tables_sum_per_sec: 'NaN',
              m_tmp_table_sizes_sum_per_sec: 'NaN',
              m_qc_hit_sum_per_sec: 'NaN',
              m_full_scan_sum_per_sec: 0.8,
              m_full_join_sum_per_sec: 'NaN',
              m_tmp_table_sum_per_sec: 'NaN',
              m_tmp_table_on_disk_sum_per_sec: 'NaN',
              m_filesort_sum_per_sec: 'NaN',
              m_filesort_on_disk_sum_per_sec: 'NaN',
              m_select_full_range_join_sum_per_sec: 'NaN',
              m_select_range_sum_per_sec: 'NaN',
              m_select_range_check_sum_per_sec: 'NaN',
              m_sort_range_sum_per_sec: 'NaN',
              m_sort_rows_sum_per_sec: 'NaN',
              m_sort_scan_sum_per_sec: 'NaN',
              m_no_index_used_sum_per_sec: 0.4,
              m_no_good_index_used_sum_per_sec: 'NaN',
              m_docs_returned_sum_per_sec: 'NaN',
              m_response_length_sum_per_sec: 'NaN',
              m_docs_scanned_sum_per_sec: 'NaN',
              m_shared_blks_hit_sum_per_sec: 'NaN',
              m_shared_blks_read_sum_per_sec: 'NaN',
              m_shared_blks_dirtied_sum_per_sec: 'NaN',
              m_shared_blks_written_sum_per_sec: 'NaN',
              m_local_blks_hit_sum_per_sec: 'NaN',
              m_local_blks_read_sum_per_sec: 'NaN',
              m_local_blks_dirtied_sum_per_sec: 'NaN',
              m_local_blks_written_sum_per_sec: 'NaN',
              m_temp_blks_read_sum_per_sec: 'NaN',
              m_temp_blks_written_sum_per_sec: 'NaN',
              m_blk_read_time_sum_per_sec: 'NaN',
              m_blk_write_time_sum_per_sec: 'NaN',
            },
            {
              point: 7,
              time_frame: 360,
              timestamp: '2020-01-28T14:04:00Z',
              load: 0.00064309366,
              num_queries_per_sec: 0.4,
              m_query_time_sum_per_sec: 0.00064309366,
              m_lock_time_sum_per_sec: 0.00006376389,
              m_rows_sent_sum_per_sec: 200,
              m_rows_examined_sum_per_sec: 200,
              m_rows_affected_sum_per_sec: 'NaN',
              m_rows_read_sum_per_sec: 'NaN',
              m_merge_passes_sum_per_sec: 'NaN',
              m_innodb_io_r_ops_sum_per_sec: 'NaN',
              m_innodb_io_r_bytes_sum_per_sec: 'NaN',
              m_innodb_io_r_wait_sum_per_sec: 'NaN',
              m_innodb_rec_lock_wait_sum_per_sec: 'NaN',
              m_innodb_queue_wait_sum_per_sec: 'NaN',
              m_innodb_pages_distinct_sum_per_sec: 'NaN',
              m_query_length_sum_per_sec: 'NaN',
              m_bytes_sent_sum_per_sec: 'NaN',
              m_tmp_tables_sum_per_sec: 0.4,
              m_tmp_disk_tables_sum_per_sec: 'NaN',
              m_tmp_table_sizes_sum_per_sec: 'NaN',
              m_qc_hit_sum_per_sec: 'NaN',
              m_full_scan_sum_per_sec: 0.8,
              m_full_join_sum_per_sec: 'NaN',
              m_tmp_table_sum_per_sec: 'NaN',
              m_tmp_table_on_disk_sum_per_sec: 'NaN',
              m_filesort_sum_per_sec: 'NaN',
              m_filesort_on_disk_sum_per_sec: 'NaN',
              m_select_full_range_join_sum_per_sec: 'NaN',
              m_select_range_sum_per_sec: 'NaN',
              m_select_range_check_sum_per_sec: 'NaN',
              m_sort_range_sum_per_sec: 'NaN',
              m_sort_rows_sum_per_sec: 'NaN',
              m_sort_scan_sum_per_sec: 'NaN',
              m_no_index_used_sum_per_sec: 0.4,
              m_no_good_index_used_sum_per_sec: 'NaN',
              m_docs_returned_sum_per_sec: 'NaN',
              m_response_length_sum_per_sec: 'NaN',
              m_docs_scanned_sum_per_sec: 'NaN',
              m_shared_blks_hit_sum_per_sec: 'NaN',
              m_shared_blks_read_sum_per_sec: 'NaN',
              m_shared_blks_dirtied_sum_per_sec: 'NaN',
              m_shared_blks_written_sum_per_sec: 'NaN',
              m_local_blks_hit_sum_per_sec: 'NaN',
              m_local_blks_read_sum_per_sec: 'NaN',
              m_local_blks_dirtied_sum_per_sec: 'NaN',
              m_local_blks_written_sum_per_sec: 'NaN',
              m_temp_blks_read_sum_per_sec: 'NaN',
              m_temp_blks_written_sum_per_sec: 'NaN',
              m_blk_read_time_sum_per_sec: 'NaN',
              m_blk_write_time_sum_per_sec: 'NaN',
            },
            {
              point: 8,
              time_frame: 360,
              timestamp: '2020-01-28T13:58:00Z',
              load: 0.00066834426,
              num_queries_per_sec: 0.4,
              m_query_time_sum_per_sec: 0.00066834426,
              m_lock_time_sum_per_sec: 0.00006412778,
              m_rows_sent_sum_per_sec: 200,
              m_rows_examined_sum_per_sec: 200,
              m_rows_affected_sum_per_sec: 'NaN',
              m_rows_read_sum_per_sec: 'NaN',
              m_merge_passes_sum_per_sec: 'NaN',
              m_innodb_io_r_ops_sum_per_sec: 'NaN',
              m_innodb_io_r_bytes_sum_per_sec: 'NaN',
              m_innodb_io_r_wait_sum_per_sec: 'NaN',
              m_innodb_rec_lock_wait_sum_per_sec: 'NaN',
              m_innodb_queue_wait_sum_per_sec: 'NaN',
              m_innodb_pages_distinct_sum_per_sec: 'NaN',
              m_query_length_sum_per_sec: 'NaN',
              m_bytes_sent_sum_per_sec: 'NaN',
              m_tmp_tables_sum_per_sec: 0.4,
              m_tmp_disk_tables_sum_per_sec: 'NaN',
              m_tmp_table_sizes_sum_per_sec: 'NaN',
              m_qc_hit_sum_per_sec: 'NaN',
              m_full_scan_sum_per_sec: 0.8,
              m_full_join_sum_per_sec: 'NaN',
              m_tmp_table_sum_per_sec: 'NaN',
              m_tmp_table_on_disk_sum_per_sec: 'NaN',
              m_filesort_sum_per_sec: 'NaN',
              m_filesort_on_disk_sum_per_sec: 'NaN',
              m_select_full_range_join_sum_per_sec: 'NaN',
              m_select_range_sum_per_sec: 'NaN',
              m_select_range_check_sum_per_sec: 'NaN',
              m_sort_range_sum_per_sec: 'NaN',
              m_sort_rows_sum_per_sec: 'NaN',
              m_sort_scan_sum_per_sec: 'NaN',
              m_no_index_used_sum_per_sec: 0.4,
              m_no_good_index_used_sum_per_sec: 'NaN',
              m_docs_returned_sum_per_sec: 'NaN',
              m_response_length_sum_per_sec: 'NaN',
              m_docs_scanned_sum_per_sec: 'NaN',
              m_shared_blks_hit_sum_per_sec: 'NaN',
              m_shared_blks_read_sum_per_sec: 'NaN',
              m_shared_blks_dirtied_sum_per_sec: 'NaN',
              m_shared_blks_written_sum_per_sec: 'NaN',
              m_local_blks_hit_sum_per_sec: 'NaN',
              m_local_blks_read_sum_per_sec: 'NaN',
              m_local_blks_dirtied_sum_per_sec: 'NaN',
              m_local_blks_written_sum_per_sec: 'NaN',
              m_temp_blks_read_sum_per_sec: 'NaN',
              m_temp_blks_written_sum_per_sec: 'NaN',
              m_blk_read_time_sum_per_sec: 'NaN',
              m_blk_write_time_sum_per_sec: 'NaN',
            },
            {
              point: 9,
              time_frame: 360,
              timestamp: '2020-01-28T13:52:00Z',
              load: 0.0006332789,
              num_queries_per_sec: 0.4027778,
              m_query_time_sum_per_sec: 0.0006332789,
              m_lock_time_sum_per_sec: 0.00005917778,
              m_rows_sent_sum_per_sec: 201.38889,
              m_rows_examined_sum_per_sec: 201.38889,
              m_rows_affected_sum_per_sec: 'NaN',
              m_rows_read_sum_per_sec: 'NaN',
              m_merge_passes_sum_per_sec: 'NaN',
              m_innodb_io_r_ops_sum_per_sec: 'NaN',
              m_innodb_io_r_bytes_sum_per_sec: 'NaN',
              m_innodb_io_r_wait_sum_per_sec: 'NaN',
              m_innodb_rec_lock_wait_sum_per_sec: 'NaN',
              m_innodb_queue_wait_sum_per_sec: 'NaN',
              m_innodb_pages_distinct_sum_per_sec: 'NaN',
              m_query_length_sum_per_sec: 'NaN',
              m_bytes_sent_sum_per_sec: 'NaN',
              m_tmp_tables_sum_per_sec: 0.4027778,
              m_tmp_disk_tables_sum_per_sec: 'NaN',
              m_tmp_table_sizes_sum_per_sec: 'NaN',
              m_qc_hit_sum_per_sec: 'NaN',
              m_full_scan_sum_per_sec: 0.8055556,
              m_full_join_sum_per_sec: 'NaN',
              m_tmp_table_sum_per_sec: 'NaN',
              m_tmp_table_on_disk_sum_per_sec: 'NaN',
              m_filesort_sum_per_sec: 'NaN',
              m_filesort_on_disk_sum_per_sec: 'NaN',
              m_select_full_range_join_sum_per_sec: 'NaN',
              m_select_range_sum_per_sec: 'NaN',
              m_select_range_check_sum_per_sec: 'NaN',
              m_sort_range_sum_per_sec: 'NaN',
              m_sort_rows_sum_per_sec: 'NaN',
              m_sort_scan_sum_per_sec: 'NaN',
              m_no_index_used_sum_per_sec: 0.4027778,
              m_no_good_index_used_sum_per_sec: 'NaN',
              m_docs_returned_sum_per_sec: 'NaN',
              m_response_length_sum_per_sec: 'NaN',
              m_docs_scanned_sum_per_sec: 'NaN',
              m_shared_blks_hit_sum_per_sec: 'NaN',
              m_shared_blks_read_sum_per_sec: 'NaN',
              m_shared_blks_dirtied_sum_per_sec: 'NaN',
              m_shared_blks_written_sum_per_sec: 'NaN',
              m_local_blks_hit_sum_per_sec: 'NaN',
              m_local_blks_read_sum_per_sec: 'NaN',
              m_local_blks_dirtied_sum_per_sec: 'NaN',
              m_local_blks_written_sum_per_sec: 'NaN',
              m_temp_blks_read_sum_per_sec: 'NaN',
              m_temp_blks_written_sum_per_sec: 'NaN',
              m_blk_read_time_sum_per_sec: 'NaN',
              m_blk_write_time_sum_per_sec: 'NaN',
            },
            {
              point: 10,
              time_frame: 360,
              timestamp: '2020-01-28T13:46:00Z',
              load: 0.0008889391,
              num_queries_per_sec: 0.44166666,
              m_query_time_sum_per_sec: 0.0008889391,
              m_lock_time_sum_per_sec: 0.000071194445,
              m_rows_sent_sum_per_sec: 220.83333,
              m_rows_examined_sum_per_sec: 220.83333,
              m_rows_affected_sum_per_sec: 'NaN',
              m_rows_read_sum_per_sec: 'NaN',
              m_merge_passes_sum_per_sec: 'NaN',
              m_innodb_io_r_ops_sum_per_sec: 'NaN',
              m_innodb_io_r_bytes_sum_per_sec: 'NaN',
              m_innodb_io_r_wait_sum_per_sec: 'NaN',
              m_innodb_rec_lock_wait_sum_per_sec: 'NaN',
              m_innodb_queue_wait_sum_per_sec: 'NaN',
              m_innodb_pages_distinct_sum_per_sec: 'NaN',
              m_query_length_sum_per_sec: 'NaN',
              m_bytes_sent_sum_per_sec: 'NaN',
              m_tmp_tables_sum_per_sec: 0.44166666,
              m_tmp_disk_tables_sum_per_sec: 'NaN',
              m_tmp_table_sizes_sum_per_sec: 'NaN',
              m_qc_hit_sum_per_sec: 'NaN',
              m_full_scan_sum_per_sec: 0.8833333,
              m_full_join_sum_per_sec: 'NaN',
              m_tmp_table_sum_per_sec: 'NaN',
              m_tmp_table_on_disk_sum_per_sec: 'NaN',
              m_filesort_sum_per_sec: 'NaN',
              m_filesort_on_disk_sum_per_sec: 'NaN',
              m_select_full_range_join_sum_per_sec: 'NaN',
              m_select_range_sum_per_sec: 'NaN',
              m_select_range_check_sum_per_sec: 'NaN',
              m_sort_range_sum_per_sec: 'NaN',
              m_sort_rows_sum_per_sec: 'NaN',
              m_sort_scan_sum_per_sec: 'NaN',
              m_no_index_used_sum_per_sec: 0.44166666,
              m_no_good_index_used_sum_per_sec: 'NaN',
              m_docs_returned_sum_per_sec: 'NaN',
              m_response_length_sum_per_sec: 'NaN',
              m_docs_scanned_sum_per_sec: 'NaN',
              m_shared_blks_hit_sum_per_sec: 'NaN',
              m_shared_blks_read_sum_per_sec: 'NaN',
              m_shared_blks_dirtied_sum_per_sec: 'NaN',
              m_shared_blks_written_sum_per_sec: 'NaN',
              m_local_blks_hit_sum_per_sec: 'NaN',
              m_local_blks_read_sum_per_sec: 'NaN',
              m_local_blks_dirtied_sum_per_sec: 'NaN',
              m_local_blks_written_sum_per_sec: 'NaN',
              m_temp_blks_read_sum_per_sec: 'NaN',
              m_temp_blks_written_sum_per_sec: 'NaN',
              m_blk_read_time_sum_per_sec: 'NaN',
              m_blk_write_time_sum_per_sec: 'NaN',
            },
            { point: 11, time_frame: 360, timestamp: '2020-01-28T13:40:00Z' },
            { point: 12, time_frame: 360, timestamp: '2020-01-28T13:34:00Z' },
            { point: 13, time_frame: 360, timestamp: '2020-01-28T13:28:00Z' },
            { point: 14, time_frame: 360, timestamp: '2020-01-28T13:22:00Z' },
            { point: 15, time_frame: 360, timestamp: '2020-01-28T13:16:00Z' },
            { point: 16, time_frame: 360, timestamp: '2020-01-28T13:10:00Z' },
            { point: 17, time_frame: 360, timestamp: '2020-01-28T13:04:00Z' },
            { point: 18, time_frame: 360, timestamp: '2020-01-28T12:58:00Z' },
            { point: 19, time_frame: 360, timestamp: '2020-01-28T12:52:00Z' },
            { point: 20, time_frame: 360, timestamp: '2020-01-28T12:46:00Z' },
            { point: 21, time_frame: 360, timestamp: '2020-01-28T12:40:00Z' },
            { point: 22, time_frame: 360, timestamp: '2020-01-28T12:34:00Z' },
            { point: 23, time_frame: 360, timestamp: '2020-01-28T12:28:00Z' },
            { point: 24, time_frame: 360, timestamp: '2020-01-28T12:22:00Z' },
            { point: 25, time_frame: 360, timestamp: '2020-01-28T12:16:00Z' },
            { point: 26, time_frame: 360, timestamp: '2020-01-28T12:10:00Z' },
            { point: 27, time_frame: 360, timestamp: '2020-01-28T12:04:00Z' },
            { point: 28, time_frame: 360, timestamp: '2020-01-28T11:58:00Z' },
            { point: 29, time_frame: 360, timestamp: '2020-01-28T11:52:00Z' },
            { point: 30, time_frame: 360, timestamp: '2020-01-28T11:46:00Z' },
            { point: 31, time_frame: 360, timestamp: '2020-01-28T11:40:00Z' },
            { point: 32, time_frame: 360, timestamp: '2020-01-28T11:34:00Z' },
            { point: 33, time_frame: 360, timestamp: '2020-01-28T11:28:00Z' },
            { point: 34, time_frame: 360, timestamp: '2020-01-28T11:22:00Z' },
            { point: 35, time_frame: 360, timestamp: '2020-01-28T11:16:00Z' },
            { point: 36, time_frame: 360, timestamp: '2020-01-28T11:10:00Z' },
            { point: 37, time_frame: 360, timestamp: '2020-01-28T11:04:00Z' },
            { point: 38, time_frame: 360, timestamp: '2020-01-28T10:58:00Z' },
            { point: 39, time_frame: 360, timestamp: '2020-01-28T10:52:00Z' },
            { point: 40, time_frame: 360, timestamp: '2020-01-28T10:46:00Z' },
            { point: 41, time_frame: 360, timestamp: '2020-01-28T10:40:00Z' },
            { point: 42, time_frame: 360, timestamp: '2020-01-28T10:34:00Z' },
            { point: 43, time_frame: 360, timestamp: '2020-01-28T10:28:00Z' },
            { point: 44, time_frame: 360, timestamp: '2020-01-28T10:22:00Z' },
            { point: 45, time_frame: 360, timestamp: '2020-01-28T10:16:00Z' },
            { point: 46, time_frame: 360, timestamp: '2020-01-28T10:10:00Z' },
            { point: 47, time_frame: 360, timestamp: '2020-01-28T10:04:00Z' },
            { point: 48, time_frame: 360, timestamp: '2020-01-28T09:58:00Z' },
            { point: 49, time_frame: 360, timestamp: '2020-01-28T09:52:00Z' },
            { point: 50, time_frame: 360, timestamp: '2020-01-28T09:46:00Z' },
            { point: 51, time_frame: 360, timestamp: '2020-01-28T09:40:00Z' },
            { point: 52, time_frame: 360, timestamp: '2020-01-28T09:34:00Z' },
            { point: 53, time_frame: 360, timestamp: '2020-01-28T09:28:00Z' },
            { point: 54, time_frame: 360, timestamp: '2020-01-28T09:22:00Z' },
            { point: 55, time_frame: 360, timestamp: '2020-01-28T09:16:00Z' },
            { point: 56, time_frame: 360, timestamp: '2020-01-28T09:10:00Z' },
            { point: 57, time_frame: 360, timestamp: '2020-01-28T09:04:00Z' },
            { point: 58, time_frame: 360, timestamp: '2020-01-28T08:58:00Z' },
            { point: 59, time_frame: 360, timestamp: '2020-01-28T08:52:00Z' },
            { point: 60, time_frame: 360, timestamp: '2020-01-28T08:46:00Z' },
            { point: 61, time_frame: 360, timestamp: '2020-01-28T08:40:00Z' },
            { point: 62, time_frame: 360, timestamp: '2020-01-28T08:34:00Z' },
            { point: 63, time_frame: 360, timestamp: '2020-01-28T08:28:00Z' },
            { point: 64, time_frame: 360, timestamp: '2020-01-28T08:22:00Z' },
            { point: 65, time_frame: 360, timestamp: '2020-01-28T08:16:00Z' },
            { point: 66, time_frame: 360, timestamp: '2020-01-28T08:10:00Z' },
            { point: 67, time_frame: 360, timestamp: '2020-01-28T08:04:00Z' },
            { point: 68, time_frame: 360, timestamp: '2020-01-28T07:58:00Z' },
            { point: 69, time_frame: 360, timestamp: '2020-01-28T07:52:00Z' },
            { point: 70, time_frame: 360, timestamp: '2020-01-28T07:46:00Z' },
            { point: 71, time_frame: 360, timestamp: '2020-01-28T07:40:00Z' },
            { point: 72, time_frame: 360, timestamp: '2020-01-28T07:34:00Z' },
            { point: 73, time_frame: 360, timestamp: '2020-01-28T07:28:00Z' },
            { point: 74, time_frame: 360, timestamp: '2020-01-28T07:22:00Z' },
            { point: 75, time_frame: 360, timestamp: '2020-01-28T07:16:00Z' },
            { point: 76, time_frame: 360, timestamp: '2020-01-28T07:10:00Z' },
            { point: 77, time_frame: 360, timestamp: '2020-01-28T07:04:00Z' },
            { point: 78, time_frame: 360, timestamp: '2020-01-28T06:58:00Z' },
            { point: 79, time_frame: 360, timestamp: '2020-01-28T06:52:00Z' },
            { point: 80, time_frame: 360, timestamp: '2020-01-28T06:46:00Z' },
            { point: 81, time_frame: 360, timestamp: '2020-01-28T06:40:00Z' },
            { point: 82, time_frame: 360, timestamp: '2020-01-28T06:34:00Z' },
            { point: 83, time_frame: 360, timestamp: '2020-01-28T06:28:00Z' },
            { point: 84, time_frame: 360, timestamp: '2020-01-28T06:22:00Z' },
            { point: 85, time_frame: 360, timestamp: '2020-01-28T06:16:00Z' },
            { point: 86, time_frame: 360, timestamp: '2020-01-28T06:10:00Z' },
            { point: 87, time_frame: 360, timestamp: '2020-01-28T06:04:00Z' },
            { point: 88, time_frame: 360, timestamp: '2020-01-28T05:58:00Z' },
            { point: 89, time_frame: 360, timestamp: '2020-01-28T05:52:00Z' },
            { point: 90, time_frame: 360, timestamp: '2020-01-28T05:46:00Z' },
            { point: 91, time_frame: 360, timestamp: '2020-01-28T05:40:00Z' },
            { point: 92, time_frame: 360, timestamp: '2020-01-28T05:34:00Z' },
            { point: 93, time_frame: 360, timestamp: '2020-01-28T05:28:00Z' },
            { point: 94, time_frame: 360, timestamp: '2020-01-28T05:22:00Z' },
            { point: 95, time_frame: 360, timestamp: '2020-01-28T05:16:00Z' },
            { point: 96, time_frame: 360, timestamp: '2020-01-28T05:10:00Z' },
            { point: 97, time_frame: 360, timestamp: '2020-01-28T05:04:00Z' },
            { point: 98, time_frame: 360, timestamp: '2020-01-28T04:58:00Z' },
            { point: 99, time_frame: 360, timestamp: '2020-01-28T04:52:00Z' },
            { point: 100, time_frame: 360, timestamp: '2020-01-28T04:46:00Z' },
            { point: 101, time_frame: 360, timestamp: '2020-01-28T04:40:00Z' },
            { point: 102, time_frame: 360, timestamp: '2020-01-28T04:34:00Z' },
            { point: 103, time_frame: 360, timestamp: '2020-01-28T04:28:00Z' },
            { point: 104, time_frame: 360, timestamp: '2020-01-28T04:22:00Z' },
            { point: 105, time_frame: 360, timestamp: '2020-01-28T04:16:00Z' },
            { point: 106, time_frame: 360, timestamp: '2020-01-28T04:10:00Z' },
            { point: 107, time_frame: 360, timestamp: '2020-01-28T04:04:00Z' },
            { point: 108, time_frame: 360, timestamp: '2020-01-28T03:58:00Z' },
            { point: 109, time_frame: 360, timestamp: '2020-01-28T03:52:00Z' },
            { point: 110, time_frame: 360, timestamp: '2020-01-28T03:46:00Z' },
            { point: 111, time_frame: 360, timestamp: '2020-01-28T03:40:00Z' },
            { point: 112, time_frame: 360, timestamp: '2020-01-28T03:34:00Z' },
            { point: 113, time_frame: 360, timestamp: '2020-01-28T03:28:00Z' },
            { point: 114, time_frame: 360, timestamp: '2020-01-28T03:22:00Z' },
            { point: 115, time_frame: 360, timestamp: '2020-01-28T03:16:00Z' },
            { point: 116, time_frame: 360, timestamp: '2020-01-28T03:10:00Z' },
            { point: 117, time_frame: 360, timestamp: '2020-01-28T03:04:00Z' },
            { point: 118, time_frame: 360, timestamp: '2020-01-28T02:58:00Z' },
            { point: 119, time_frame: 360, timestamp: '2020-01-28T02:52:00Z' },
          ],
          totals: {
            blk_read_time: {},
            blk_write_time: {},
            bytes_sent: {
              rate: 0.009166666,
              cnt: 3,
              sum: 396,
              max: 132,
              avg: 132,
              p99: 0.08136429,
            },
            docs_returned: {},
            docs_scanned: {},
            filesort: {},
            filesort_on_disk: {},
            full_join: { rate: 0.007777778, sum: 336 },
            full_scan: { rate: 0.33662036, sum: 14542 },
            innodb_io_r_bytes: {},
            innodb_io_r_ops: {},
            innodb_io_r_wait: {},
            innodb_pages_distinct: {},
            innodb_queue_wait: {},
            innodb_rec_lock_wait: {},
            local_blks_dirtied: {},
            local_blks_hit: {},
            local_blks_read: {},
            local_blks_written: {},
            lock_time: {
              rate: 0.0018818211,
              cnt: 682061,
              sum: 81.29467,
              max: 0.000123,
              avg: 0.00011918973,
              p99: 7.150195e-8,
            },
            merge_passes: {},
            no_good_index_used: {},
            no_index_used: { rate: 0.29, sum: 12528 },
            num_queries: { rate: 16.689745, sum: 720997 },
            num_queries_with_errors: { rate: 0.0025925925, sum: 112 },
            num_queries_with_warnings: {},
            qc_hit: {},
            query_length: {},
            query_time: {
              rate: 1281024000,
              cnt: 720997,
              sum: 55340234000000,
              max: 18446744000000,
              avg: 76755150,
              p99: 11370502000,
            },
            response_length: {},
            rows_affected: { cnt: 3 },
            rows_examined: {
              rate: 90.09648,
              cnt: 685862,
              sum: 3892168,
              max: 1,
              avg: 5.6748557,
              p99: 0.00061639614,
            },
            rows_read: {},
            rows_sent: {
              rate: 84.37261,
              cnt: 713998,
              sum: 3644897,
              max: 1,
              avg: 5.1049123,
              p99: 0.00061639614,
            },
            select_full_range_join: {},
            select_range: {},
            select_range_check: {},
            shared_blks_dirtied: { rate: 0.00027777778, sum: 12 },
            shared_blks_hit: { rate: 0.5125463, sum: 22142 },
            shared_blks_read: { rate: 0.0003935185, sum: 17 },
            shared_blks_written: {},
            sort_range: {},
            sort_rows: { rate: 0.01037037, sum: 448 },
            sort_scan: { rate: 0.0025925925, sum: 112 },
            temp_blks_read: {},
            temp_blks_written: {},
            tmp_disk_tables: {
              rate: 0.031064814,
              cnt: 1342,
              sum: 1342,
              avg: 1,
            },
            tmp_table: {},
            tmp_table_on_disk: {},
            tmp_table_sizes: {},
            tmp_tables: {
              rate: 0.19935185,
              cnt: 7270,
              sum: 8612,
              avg: 1.1845943,
            },
          },
        };
        const withData =
          Object.entries(
            response.metrics ? response.metrics : response['totals']
          )
            .filter(metricData => Object.keys(metricData[1]).length)
            .filter(
              metricData =>
                !(
                  metricData[1]['cnt'] !== 0 &&
                  metricData[1]['sum'] === undefined
                )
            )
            .map(withDataItem => {
              const sparklineData = this.createSparklineModel(
                response.sparkline,
                withDataItem[0]
              );
              return new MetricModel(withDataItem, sparklineData);
            }) || [];
        const withDataTotals =
          Object.entries(response['totals'])
            .filter(metricData => Object.keys(metricData[1]).length)
            .map(withDataTotalsItem => new MetricModel(withDataTotalsItem))
            .filter(totalsItem =>
              withData.some(
                metricsItem => metricsItem.metricName === totalsItem.metricName
              )
            ) || [];
        return {
          metrics: withData,
          totals: withDataTotals,
        };
      }),
      catchError(err => of([]))
    );
  }

  sortDetails(a, b) {
    const order = [
      'num_queries',
      'num_queries_with_errors',
      'num_queries_with_warnings',
      'query_time',
      'lock_time',
      'rows_sent',
      'rows_examined',
      '',
    ];

    let indA = order.indexOf(a['metricName']);
    let indB = order.indexOf(b['metricName']);

    if (indA === -1) {
      indA = order.length - 1;
    }

    if (indB === -1) {
      indB = order.length - 1;
    }

    return indA < indB ? -1 : 1;
  }
}
