#!/usr/bin/env bash
BASEDIR=$(cd "$(dirname "$0")"; pwd)
LISTEN="${LISTEN:-":LISTEN"}"
HOST="${LISTEN%:*}"
PORT="${LISTEN#*:}"
BG="${BG:-"yes"}"

app_is_running() {
   pid=$(ps ax | grep "percona-qan-app-$PORT" | grep -v grep | awk '{print $1}')
   [ "$pid" ] && return 0 # running
   return 1 # not running
}

if app_is_running; then
   kill $pid
fi

cmd="python -c \"import BaseHTTPServer as bhs, SimpleHTTPServer as shs; bhs.HTTPServer(('$HOST', $PORT), shs.SimpleHTTPRequestHandler).serve_forever() # percona-qan-app-$PORT\""
if [ "$BG" = "yes" ]; then
   eval "$cmd >> percona-qan-app.log 2>&1 &"
   pid=$!
   if [ $? -ne 0 ]; then
      echo "Error started Percona QAN app. Check the log file: $BASEDIR/percona-qan-app.log" >&2
      exit 1
   fi
   echo "Percona Query Analytics app running as PID $pid"
else
   echo "Percona Query Analytics app listening on $LISTEN..."
   eval "$cmd"
fi
