#!/usr/bin/env bash

BASEDIR=$(cd "$(dirname "$0")"; pwd)
. "$BASEDIR/start"

FIXPIDFILE="no"
if app_is_running; then
   kill $PID
   rm -f "$PIDFILE"
   echo "Stopped Percona Query Analytics app"
else
   echo "Percona Query Analytics app is not running"
fi
